# Generated by Django 5.1.5 on 2025-01-20 15:53

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', tinymce.models.HTMLField(default='')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='media/image')),
                ('category', models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('HTML', 'HTML'), ('Tips & Tricks', 'Tips & Tricks'), ('CSS', 'CSS'), ('Bootstrap', 'BOOTSTRAP'), ('Python', 'Python'), ('JAVA', 'JAVA'), ('JavaScript', 'JavaScript'), ('Django', 'Django')], max_length=15, null=True)),
                ('summary', models.TextField(null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('HTML', 'HTML'), ('Tips & Tricks', 'Tips & Tricks'), ('CSS', 'CSS'), ('Bootstrap', 'BOOTSTRAP'), ('Python', 'Python'), ('JAVA', 'JAVA'), ('JavaScript', 'JavaScript'), ('Django', 'Django')])),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.TextField(max_length=50, null=True)),
                ('contact_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('feedback', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('recommend', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='media/image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
