# Generated by Django 5.1.1 on 2024-10-12 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='articles')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('AI', 'ARTIFICIAL INTELLIGENCE'), ('ML', 'MACHINE LEARNING'), ('IOT', 'INTERNET OF THINGS'), ('AUTO', 'AUTOMATIONS')], max_length=10)),
            ],
        ),
    ]
