# Generated by Django 5.1.1 on 2024-10-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contactme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactme',
        ),
    ]
