# Generated by Django 5.1.1 on 2024-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('text', models.TextField(max_length=50, null=True)),
                ('contact_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
