# Generated by Django 5.1.1 on 2024-10-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=10)),
                ('prompt', models.CharField(max_length=20)),
                ('slide_image', models.ImageField(upload_to='sliders')),
            ],
        ),
    ]
