# Generated by Django 5.1.1 on 2024-10-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slider',
        ),
    ]
