# Generated by Django 5.1.1 on 2024-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, null=True)),
                ('prompt', models.CharField(max_length=8, null=True)),
                ('slider_image', models.ImageField(upload_to='sliders')),
                ('updatedon', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
