# Generated by Django 5.1.1 on 2024-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_sliders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='prompt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
