# Generated by Django 5.1.1 on 2024-10-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_sliders_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sliders',
        ),
    ]
