# Generated by Django 5.1.1 on 2024-10-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_delete_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cate',
            field=models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('AI', 'ARTIFICIAL INTELLIGENCE'), ('ML', 'MACHINE LEARNING'), ('IOT', 'INTERNET OF THINGS'), ('AUTO', 'AUTOMATIONS')], max_length=5, null=True),
        ),
    ]
