# Generated by Django 5.1.3 on 2024-11-23 09:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_blog_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
