# Generated by Django 5.1.3 on 2024-11-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cate',
            field=models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('AI', 'ARTIFICIAL INTELLIGENCE'), ('CODE', 'CODING'), ('MS', 'MICROSOFT'), ('AUTO', 'AUTOMATIONS')], max_length=5, null=True),
        ),
    ]
