# Generated by Django 5.1.3 on 2024-11-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cate',
            field=models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('HTML', 'HTML'), ('CODE', 'CODING'), ('CSS', 'CSS'), ('BTS', 'BOOTSTRAP'), ('PYT', 'PYTHON'), ('JAVA', 'JAVA'), ('JS', 'JAVASCRIPT'), ('DJF', 'DJANGO FRAMEWORK')], max_length=5, null=True),
        ),
    ]
