# Generated by Django 5.1.3 on 2024-11-30 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_blog_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedart', to='user.blog')),
            ],
        ),
    ]
