# Generated by Django 5.1.3 on 2024-11-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_relatedarticles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedArticles',
        ),
    ]
