# Generated by Django 5.1.3 on 2024-11-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_delete_relatedarticles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cate',
            new_name='category',
        ),
    ]
