# Generated by Django 5.1.3 on 2024-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_rename_cate_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('HTML', 'HTML'), ('Tips & Tricks', 'Tips & Tricks'), ('CSS', 'CSS'), ('Bootstrap', 'BOOTSTRAP'), ('Python', 'Python'), ('JAVA', 'JAVA'), ('JavaScript', 'JavaScript'), ('Django', 'Django')], max_length=15, null=True),
        ),
    ]
