# Generated by Django 5.1.3 on 2024-12-02 13:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_blog_summary_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='media/image')),
                ('category_title', models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('HTML', 'HTML'), ('Tips & Tricks', 'Tips & Tricks'), ('CSS', 'CSS'), ('Bootstrap', 'BOOTSTRAP'), ('Python', 'Python'), ('JAVA', 'JAVA'), ('JavaScript', 'JavaScript'), ('Django', 'Django')], max_length=15, null=True)),
            ],
        ),
    ]
