# Generated by Django 5.1.3 on 2024-12-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_categoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryimage',
        ),
    ]
