# Generated by Django 5.1.3 on 2024-12-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
