# Generated by Django 5.1.3 on 2024-12-02 16:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TECH', 'TECHNOLOGY'), ('HTML', 'HTML'), ('Tips & Tricks', 'Tips & Tricks'), ('CSS', 'CSS'), ('Bootstrap', 'BOOTSTRAP'), ('Python', 'Python'), ('JAVA', 'JAVA'), ('JavaScript', 'JavaScript'), ('Django', 'Django')])),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
