# Generated by Django 5.1.3 on 2025-01-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommendation',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
    ]
