# Generated by Django 5.1.3 on 2025-01-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_review_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='recommendation',
            new_name='recommend',
        ),
    ]
