# Generated by Django 5.1.5 on 2025-01-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email_token',
            field=models.CharField(default='helloworldwelcome', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
