# Generated by Django 5.1.5 on 2025-01-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_blog_email_token_blog_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_verified',
        ),
    ]
