# Generated by Django 5.1.5 on 2025-01-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
